site_name: AliceScript Specification
header_name : AliceScript
copyright : 'Copyright &copy; 2023 WSOFT All Rights reserved.'

docs_dir : 'docs'
site_url : 'https://spec.alice.wsoft.ws/'

repo_name : 'GitHub'
repo_url : 'https://github.com/WSOFT-Project/AliceScript-Specification/docs/'
edit_uri: 'blob/develop/docs/'
edit_uri_template: 'blob/develop/docs/{path}'

#google_analytics : 'G-9GQ0FRW2FZ'

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
#image : https://wsoft.ws/favicon.ico
#favicon_svg : https://wsoft.ws/favicon.svg
language : ja


theme: "lantana"

visible_search : true

plugins:
    - search:
        lang : 'ja'
        min_search_length: 2
    - mermaid2
    - git-revision-date
    #- macros
    - awesome-pages
    - git-authors:
        show_email_address: true
        count_empty_lines: true
        fallback_to_empty: false
        enabled: true

markdown_extensions:
    #- lantana.extensions.mdx_embedly
    #- lantana.extensions.mdx_wsid
    - attr_list
    - mdx_cards
    - pymdownx.highlight:
       anchor_linenums: true
    - admonition
    - pymdownx.arithmatex:
       generic : true
    - md_in_html
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid
    - pymdownx.snippets
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.magiclink
    - pymdownx.striphtml
